label: test
mode: frequency # frequency, threshold
ssh_address: root@192.168.0.11
target_project_dir: /home/root/sdd/tools
target_cores: 4-7
target_frequency: 101
target_threshold: 50000
duration: 10
xlim : [0.0, 10.0]
ylim : [0.0, 15.0]